.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "VBOX\-GUEST\-INSTALLER" "8" "January 2020" "vm-config-dist" "vm-config-dist Manual"
.SH "NAME"
\fBvbox\-guest\-installer\fR \- Qubes Remote Support Provider
.P
.SH "SYNOPSIS"
\fBvbox\-guest\-installer\fR
.SH "DESCRIPTION"
Installs
.SH "EXAMPLES"
\fBvbox\-guest\-installer\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
