.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "VBOX\-GUEST\-INSTALLER" "8" "January 2020" "vm-config-dist" "vm-config-dist Manual"
.SH "NAME"
\fBvbox\-guest\-installer\fR \- Install VirtualBox guest additions from ISO package
.SH "SYNOPSIS"
\fBvbox\-guest\-installer\fR
.SH "DESCRIPTION"
Installs the VirtualBox guest additions from the ISO provided by the \fBvirtualbox\-guest\-additions\-iso\fR package\.
.P
VirtualBox Guest Additions are preinstalled on most images where it makes sense for it to be installed\. You probably do not need to run this tool\.
.SH "EXAMPLES"
\fBvbox\-guest\-installer\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
