#!/bin/bash

## Copyright (C) 2017 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if command -v /usr/sbin/virt-what >/dev/null ; then
   result="$(sudo --non-interactive /usr/sbin/virt-what)"
else
   true "$0: /usr/sbin/virt-what not found. Stop."
   return 0
   exit 0
fi

if [ "$result" = "" ]; then
   true "$0: Not running in a Virtual Machine (or none detected), therefore not disabling monitor power saving. Stop."
   return 0
   exit 0
else
   true "$0: VM $result found. Continue."
fi

if [ -z "$XDG_CONFIG_DIRS" ]; then
   XDG_CONFIG_DIRS=/etc/xdg
fi
export XDG_CONFIG_DIRS=/usr/share/kde-screen-locker-disable-in-vms/:$XDG_CONFIG_DIRS
