#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

virt_what_command_exit_code="0"
command -v virt-what >/dev/null || { virt_what_command_exit_code="$?" ; true; };

if [ "$virt_what_command_exit_code" = "0" ]; then
   true "$0: virt-what found. Continue."
elif [ -x "/usr/sbin/virt-what" ]; then
   true "$0: /usr/sbin/virt-what executable. Continue."
else
   true "$0: virt-what not found. Stop."
   return 0
   exit 0
fi

xset_command_exit_code="0"
command -v xset >/dev/null || { xset_command_exit_code="$?" ; true; };

if [ ! "$xset_command_exit_code" = "0" ]; then
   true "$0: xset not installed. Stop."
   return 0
   exit 0
else
   true "$0: xset found. Continue."
fi

result="$(sudo virt-what)"

if [ "$result" = "" ]; then
   true "$0: Not running in a Virtual Machine (or none detected), therefore not disabling monitor power saving. Stop."
   return 0
   exit 0
else
   true "$0: VM $result found. Continue."
fi

(
   if [ "$(id -u)" = "0" ]; then
      true "$0: Can not run as root. Exiting."
      exit 0
   fi
   sleep 60 &
   wait "$!"
   xset s off
   xset -dpms
   exit 0
) &

return 0
exit 0
