#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

virt_what_command_exit_code="0"
command -v virt-what >/dev/null || { virt_what_command_exit_code="$?" ; true; };

if [ "$virt_what_command_exit_code" = "0" ]; then
   true
elif [ -x "/usr/sbin/virt-what" ]; then
   true
else
   return 0
fi

result="$(sudo virt-what)"

if [ "$result" = "" ]; then
   ## Not running in a Virtual Machine (or none detected),
   ## therefore not disabling monitor power saving.
   return 0
fi

(
   if [ "$(id -u)" = "0" ]; then
      true "$0: Can not run as root. Exiting."
      exit 0
   fi
   sleep 60 &
   wait "$!"
   xset s off
   xset -dpms
   exit 0
) &
